sudo: false
services: mongodb

notifications:
  email: false

language: ruby
cache: bundler
rvm:
  - 2.2.9
  - 2.3.7
  - 2.4.4

gemfile:
  - Gemfile
  - gemfiles/carrierwave-0.10.gemfile
  - gemfiles/carrierwave-0.11.gemfile
  - gemfiles/carrierwave-1.1.gemfile
  - gemfiles/carrierwave-1.2.gemfile
  - gemfiles/mongoid-3.gemfile
  - gemfiles/mongoid-4.gemfile
  - gemfiles/mongoid-5.gemfile
  - gemfiles/mongoid-6.gemfile

matrix:
  fast_finish: true
