sudo: false
services: mongodb

notifications:
  email: false

language: ruby
cache: bundler
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - jruby-19mode

gemfile:
  - Gemfile
  - gemfiles/carrierwave-0.9.gemfile
  - gemfiles/carrierwave-0.10.gemfile
  - gemfiles/carrierwave-master.gemfile
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/mongoid-5.0.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/carrierwave-master.gemfile
  fast_finish: true
